name: ci
on: push
jobs:     
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn Install
        run: yarn
      - name: Run linters
        run: yarn lint
      
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn Install
        run: yarn
      - name: TypeScript Build
        run: yarn build
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn Install
        run: yarn
      - name: Start docker services
        run: yarn cli docker start
      - name: Run Jest Tests
        run: yarn cli test jest
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn Install
        run: yarn
      - name: Start docker services
        run: yarn cli docker start
      - name: Check running network
        run: netstat -tulnp
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'http://localhost:44431'
